### PR TITLE
Add class method coroutine example

### PR DESCRIPTION
**Pull request by XertroV**
Add example demonstrating how class methods can be used as coroutines.

LMK if any issues. I am a little unsure about my usage of "function handles" and "delegate" in the comments. I gather that all delegates (aka delegate objects) are function handles, but not all function handles are delegates.

I think it's probs important to use the exact words "delegate object" somewhere since the error in openplanet logs when you try to do `startnew(obj.Method);` is:

> ERR : Can't pass class method as arg directly. Use a delegate object instead

### CODE REVIEW

**Comment by codecat** [comment]
You don't need to create your own funcdef, you can just use `CoroutineFunc` or `CoroutineFuncUserdata` instead:

```angelscript
void CoroutineFunc();
void CoroutineFuncUserdata(ref@);
```

And then to start a method you can just do this:

```angelscript
class Foo
{
  void StartMyRoutine()
  {
    startnew(CoroutineFunc(MyRoutineAsync));
  }

  void MyRoutineAsync()
  {
    // ...
  }
}
```

**Comment by XertroV** [comment]
> You don't need to create your own funcdef, you can just use `CoroutineFunc` or `CoroutineFuncUserdata` instead

Ahh, neat. I guess that these are basically funcdefs that are already provided in the global namespace?

I'll update the example to use `CoroutineFunc`.

WRT funcdefs -- I think some examples of them would still be useful to have somewhere because the AngleScript docs are a little confusing if you're not familiar with what's going on already.

**Comment by XertroV** [comment]
Also, wrt passing args to coroutines -- is there an example somewhere of how `ref@` is used?

I tried doing that with some code y'day and got it to compile but didn't find out if it worked b/c of other issues with coroutines and class methods.
I tried `cast<ref>(args)` and then cast it back to its normal type later, but I'm not sure if that's what's intended.

Instead of that I ended up making a global queue that the coroutine pulls from: https://github.com/XertroV/tm-cotd-hud/blob/3a005a368d653d387897cc12d1120334981fce12/src/DataManager.as#L315-L331

**Comment by codecat** [comment]
> I guess that these are basically funcdefs that are already provided in the global namespace?

Yes, indeed. They are the funcdef types that are passed into the `startnew()` function itself.

> WRT funcdefs -- I think some examples of them would still be useful to have somewhere because the AngleScript docs are a little confusing if you're not familiar with what's going on already.

Sure, but that's not relevant for the coroutine example. Also feels more like an Angelscript-specific thing rather than an Openplanet API example so that might not even fit in this repository.

For the coroutine userdata parameter, check out these snippets from Plugin Manager:

https://github.com/openplanet-nl/plugin-manager/blob/5b3b479b90cc02c52570c1a1c86b53e8cf1b900a/src/MenuMain.as#L29-L30

https://github.com/openplanet-nl/plugin-manager/blob/9cdcdd397ad481d8bccbb5c940e9da1250755d78/src/Update.as#L40-L42

**Comment by XertroV** [comment]
> For the coroutine userdata parameter, check out these snippets from Plugin Manager:

Thanks!

Example update now showing both `CoroutineFunc` and `CoroutineFuncUserdata` usage.

**Comment by codecat** [comment]
Thanks! 🎉

**Pull request merged**
